// frontend/pages/admin/login.vue
<template>
  <div class="min-h-screen flex items-center justify-center px-4">
    <div class="cute-card max-w-md w-full">
      <div class="text-center mb-8">
        <div class="text-4xl mb-4">🔐</div>
        <h1 class="cute-title">管理员登录</h1>
        <p class="cute-subtitle mt-2">请输入账号密码</p>
      </div>

      <form @submit.prevent="handleLogin" class="space-y-4">
        <div>
          <label class="block text-sm font-medium text-primary-600 mb-2">用户名</label>
          <input
            v-model="form.username"
            type="text"
            class="cute-input"
            placeholder="请输入用户名"
            required
          />
        </div>

        <div>
          <label class="block text-sm font-medium text-primary-600 mb-2">密码</label>
          <input
            v-model="form.password"
            type="password"
            class="cute-input"
            placeholder="请输入密码"
            required
          />
        </div>

        <p v-if="error" class="text-red-500 text-sm text-center">{{ error }}</p>

        <button
          type="submit"
          class="cute-btn w-full"
          :disabled="loading"
        >
          <span v-if="loading" class="animate-spin mr-2">⏳</span>
          {{ loading ? '登录中...' : '登录' }}
        </button>
      </form>

      <NuxtLink 
        to="/" 
        class="block text-center mt-6 text-primary-500 hover:text-primary-600"
      >
        ← 返回首页
      </NuxtLink>
    </div>
  </div>
</template>

<script setup lang="ts">
definePageMeta({
  layout: 'admin'
})

const authStore = useAuthStore()
const router = useRouter()

const form = reactive({
  username: '',
  password: ''
})
const loading = ref(false)
const error = ref('')

const handleLogin = async () => {
  loading.value = true
  error.value = ''
  
  const result = await authStore.login(form.username, form.password)
  
  if (result.success) {
    router.push('/admin')
  } else {
    error.value = result.error
  }
  
  loading.value = false
}

onMounted(() => {
  if (authStore.isAuthenticated) {
    router.push('/admin')
  }
})
</script>

// src/pages/Login.tsx
import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { supabase } from '@/lib/supabase';
import { Lock } from 'lucide-react';

export default function Login() {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const navigate = useNavigate();

  const handleLogin = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);
    setError(null);

    try {
      const { error } = await supabase.auth.signInWithPassword({
        email,
        password,
      });

      if (error) throw error;
      navigate('/admin');
    } catch (err: any) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen flex items-center justify-center bg-zinc-950 text-zinc-100">
      <div className="w-full max-w-md p-8 bg-zinc-900/50 rounded-2xl border border-white/10 backdrop-blur-xl">
        <div className="flex justify-center mb-8">
          <div className="p-4 bg-blue-500/10 rounded-full">
            <Lock className="w-8 h-8 text-blue-500" />
          </div>
        </div>
        
        <h2 className="text-2xl font-bold text-center mb-8">Admin Login</h2>
        
        {error && (
          <div className="mb-6 p-4 bg-red-500/10 border border-red-500/20 rounded-lg text-red-400 text-sm">
            {error}
          </div>
        )}

        <form onSubmit={handleLogin} className="space-y-6">
          <div>
            <label className="block text-sm font-medium text-zinc-400 mb-2">
              Email
            </label>
            <input
              type="email"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              className="w-full px-4 py-3 bg-black/50 border border-white/10 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent transition-all"
              placeholder="admin@example.com"
              required
            />
          </div>
          
          <div>
            <label className="block text-sm font-medium text-zinc-400 mb-2">
              Password
            </label>
            <input
              type="password"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              className="w-full px-4 py-3 bg-black/50 border border-white/10 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent transition-all"
              placeholder="••••••••"
              required
            />
          </div>

          <button
            type="submit"
            disabled={loading}
            className="w-full py-3 px-4 bg-blue-600 hover:bg-blue-500 text-white font-medium rounded-lg transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
          >
            {loading ? 'Signing in...' : 'Sign In'}
          </button>
        </form>
      </div>
    </div>
  );
}
